services:
  mongo:
    image: mirror.gcr.io/library/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27020:27017"
    networks:
      - mongo-network

  calculadora:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/joaquower/webiii/backend:latest
    ports:
      - "8089:8000"
    depends_on:
      - mongo
    networks:
      - mongo-network

  frontend:
    image: ghcr.io/joaquower/webiii/frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - calculadora
    networks:
      - mongo-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    networks:
      - mongo-network
    depends_on:
      - calculadora
    pull_policy: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - mongo-network
    depends_on:
      - prometheus

networks:
  mongo-network:
    driver: bridge
    name: practicas_mongo-network  # nombre explícito para que monitoring pueda conectarse
