name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main
      - 'release/*'
    tags:
      - 'v*'
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: vars
        run: |
          # Usa GITHUB_REF para detectar si el push fue un tag
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "TAG=$TAG" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Determine image name (lowercase)
        run: |
          # Convierte el nombre del repositorio a minúsculas y añade el sufijo /backend
          IMAGE=ghcr.io/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/backend
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          echo "Building image: $IMAGE:$TAG"
          # Construye la imagen desde el directorio ./backend
          docker build -t $IMAGE:$TAG ./backend

      - name: Push Docker image
        run: |
          echo "Pushing image: $IMAGE:$TAG"
          docker push $IMAGE:$TAG
